POST http://localhost:8080/auth/realms/fincycle/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=nest
&client_secret=662ea7ed-3b52-4ee7-8987-06e4cb852a3f
&grant_type=password
&username=user1@user.com
&password=123456